### ISSUE TITLE
&'static str in public API

### ISSUE THREAD

**Issue by sciguy16** [MortenRoemer/powerplatform-dataverse-service-client#5]
Hi, what is the reason for requiring `&'static str` in the API for e.g. `Client::with_client_secret_auth`? Would you be interested in a PR to change them to `impl Into<String>` to make the API more flexible?

```rust
pub fn with_client_secret_auth(
    url: &'static str,
    tenant_id: &'static str,
    client_id: String,
    client_secret: String,
) -> Self
```

**Comment by MortenRoemer** [comment]
This seemed appropiate at the time because the url is Something that will in any usual use Case never Change during the execution of the Program.
It's not a Bad Idea to make this more flexible with traits Like AsRef or Into

But I would keep it Reference-like because there ist No good reason yet to own this value

**Comment by sciguy16** [comment]
Makes sense - for my use case I'm loading the URL etc. from configuration files at runtime, which requires calls to `Box::leak` to get the static lifetime. To keep the URL as a reference we could either store it as `&str` in the `Client` struct or convert it into a `std::borrow::Cow`:

```rust
pub struct Client<'url, A: Authenticate> {
    pub url: &'url str,
    backend: reqwest::Client,
    auth: A,
}
...
    pub fn with_client_secret_auth(
        url: &'url str,
        tenant_id: &str,
        client_id: impl Into<String>,
        client_secret: impl Into<String>,
    ) -> Self 
```
or
```rust
pub struct Client<'url, A: Authenticate> {
    pub url: Cow<'url, str>,
    backend: reqwest::Client,
    auth: A,
}
...
    pub fn with_client_secret_auth(
        url: impl Into<Cow<'url, str>>,
        tenant_id: &str,
        client_id: impl Into<String>,
        client_secret: impl Into<String>,
    ) -> Self 
```

My preference would be to use `Cow` for the flexibility to either borrow or own the URL - what do you think?

**Comment by MortenRoemer** [comment]
I agree :) I can Push Out the Change later today. I'm looking Forward to your feedback

**Comment by sciguy16** [comment]
Sounds good, thanks - I'll get a PR in :)
